name: Run tests
on:
 push:
  tags:
    - 'v*'
jobs:
  ReleaMyApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Mavern package
        run: mvn package -DskipTests
      - name: list compiled files
        run: ls -la target/
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "target/my-ecommerce-0.1.jar"
         body: |
	    The name of your branch is ${{ github.ref }}
            ${{GITHUB_REF_NAME}}
            ${{GITHUB_REPOSITORY}}
            ${{GITHUB_JOB}}

    
